TEXT_SPLITER:
  SEPARATOR: \n
  CHUNK_SIZE: 1000
  CHUNK_OVERLAP: 200


INDEX_INFO:
  INDEX_NAME: meshlennysnews
  DIMENSIONS: 1536
  METRIC: cosine
  ENVIROMENT: gcp-starter
  NAMESPACE: 'blog'

BATCH_SIZE:
  BATCH_SIZE: 120

DELETE_DATABSE:
  DELETE_DATABSE: True

