aritfacts_root: aritfacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: Data
  load_dir: artifacts/data_ingestion/vector_data.json

data_validation:
  root_dir: artifacts/data_validation
  read_data_dir: artifacts/data_ingestion/vector_data.json
  STATUS_FILE: artifacts/data_validation/status.txt

data_load:
  root_dir: artifacts/data_upload
  read_data_dir: artifacts/data_ingestion/vector_data.json
  STATUS_FILE: artifacts/data_upload/status.txt

code_structure:
  root_dir: artifacts/app_schema
  load_struct_dir: artifacts/app_schema/schema.json
  load_ignored_dir: artifacts/app_schema/ignored_files.json
  gitignore_path: .gitignore
  code_dir: .
  sructure_file: structure.txt

json_summary:
  root_dir: artifacts/json_summary
  read_schema: artifacts/app_schema/schema.json
  load_json_summary: artifacts/json_summary/json_summary.json

graph_structure:
  root_dir: artifacts/graph_structure
  graph_structure_file: artifacts/graph_structure/graph_model
  graph_json_model: artifacts/graph_structure/graph_json_model.json
  sructure_file: structure.txt


